export type Vehicle = {
  id: number
  title: string
  price: number
  oldPrice?: number
  image: string
  miles: string
  odometer: string
  match: number
  labels: string[]
}

export const mockVehicles: Vehicle[] = [
  {
    id: 1,
    title: '2023 Toyota Corolla Cross',
    price: 31_250,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '18,000mi',
    match: 39,
    labels: [],
  },
  {
    id: 2,
    title: '2022 Toyota RAV4 Hybrid',
    price: 31_250,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '24,600mi',
    match: 56,
    labels: ['Excellent Price'],
  },
  {
    id: 3,
    title: '2023 Toyota RAV4 Hybrid',
    price: 33_250,
    oldPrice: 34_995,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '21,000mi',
    match: 79,
    labels: ['Price Drop'],
  },
  {
    id: 4,
    title: '2023 Toyota RAV4 Hybrid',
    price: 33_250,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '21,000mi',
    match: 79,
    labels: [],
  },
  {
    id: 5,
    title: '2024 Toyota RAV4 Hybrid',
    price: 29_990,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '24,500mi',
    match: 85,
    labels: [],
  },
  {
    id: 6,
    title: '2022 Toyota Yaris Cross Hybrid Active',
    price: 30_250,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '16,000mi',
    match: 54,
    labels: ['Excellent Price'],
  },
  {
    id: 7,
    title: '2023 Toyota Corolla Cross',
    price: 31_250,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '18,000mi',
    match: 81,
    labels: [],
  },
  {
    id: 8,
    title: '2024 Toyota RAV4 Hybrid',
    price: 33_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '5,000mi',
    match: 57,
    labels: [],
  },
  {
    id: 9,
    title: '2020 Toyota Venza Limited Edition',
    price: 32_000,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '9,000mi',
    match: 74,
    labels: [],
  },
  {
    id: 10,
    title: '2022 Toyota Yaris Cross Hybrid Active',
    price: 24_250,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '11,050mi',
    match: 72,
    labels: ['Low Price'],
  },
  {
    id: 11,
    title: '2025 Toyota RAV4 Limited Edition',
    price: 30_900,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '15,000mi',
    match: 55,
    labels: ['Low Price'],
  },
  {
    id: 12,
    title: '2020 Toyota Corolla Cross Limited Edition',
    price: 31_250,
    oldPrice: 34_568,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '17,200mi',
    match: 76,
    labels: ['Price Drop'],
  },
  {
    id: 13,
    title: '2025 Toyota RAV4 Limited Edition',
    price: 34_250,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '21,000mi',
    match: 74,
    labels: [],
  },
  {
    id: 14,
    title: '2023 Toyota Camry XSE',
    price: 28_500,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '12,500mi',
    match: 88,
    labels: ['Good Price'],
  },
  {
    id: 15,
    title: '2024 Toyota Highlander Hybrid',
    price: 45_990,
    oldPrice: 48_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '8,200mi',
    match: 91,
    labels: ['Price Drop'],
  },
  {
    id: 16,
    title: '2022 Toyota Tacoma TRD Pro',
    price: 42_750,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '28,400mi',
    match: 67,
    labels: [],
  },
  {
    id: 17,
    title: '2023 Toyota Tundra CrewMax',
    price: 52_900,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '15,800mi',
    match: 72,
    labels: ['Excellent Price'],
  },
  {
    id: 18,
    title: '2024 Toyota Prius Prime',
    price: 34_500,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '3,200mi',
    match: 94,
    labels: ['Low Price'],
  },
  {
    id: 19,
    title: '2021 Toyota 4Runner TRD Off-Road',
    price: 39_900,
    oldPrice: 42_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '35,600mi',
    match: 63,
    labels: ['Price Drop'],
  },
  {
    id: 20,
    title: '2023 Toyota Sienna Platinum',
    price: 48_750,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '19,200mi',
    match: 78,
    labels: [],
  },
  {
    id: 21,
    title: '2024 Toyota Crown Platinum',
    price: 51_200,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '6,100mi',
    match: 86,
    labels: ['Good Price'],
  },
  {
    id: 22,
    title: '2022 Toyota GR86 Premium',
    price: 29_800,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '22,300mi',
    match: 71,
    labels: [],
  },
  {
    id: 23,
    title: '2023 Toyota Supra 3.0',
    price: 54_900,
    oldPrice: 58_200,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '11,500mi',
    match: 82,
    labels: ['Price Drop', 'Excellent Price'],
  },
  {
    id: 24,
    title: '2024 Toyota bZ4X Limited',
    price: 43_500,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '4,800mi',
    match: 89,
    labels: [],
  },
  {
    id: 25,
    title: '2021 Toyota Avalon TRD',
    price: 32_400,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '31,200mi',
    match: 58,
    labels: ['Low Price'],
  },
  {
    id: 26,
    title: '2023 Toyota C-HR Nightshade',
    price: 27_900,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '14,600mi',
    match: 75,
    labels: ['Good Price'],
  },
  {
    id: 27,
    title: '2024 Toyota Sequoia Capstone',
    price: 78_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '2,100mi',
    match: 92,
    labels: [],
  },
  {
    id: 28,
    title: '2022 Toyota GR Corolla Core',
    price: 36_900,
    oldPrice: 39_500,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '18,700mi',
    match: 84,
    labels: ['Price Drop'],
  },
  {
    id: 29,
    title: '2023 Toyota Land Cruiser',
    price: 87_500,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '9,400mi',
    match: 96,
    labels: ['Excellent Price'],
  },
  {
    id: 30,
    title: '2024 Toyota Mirai Limited',
    price: 52_800,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '1,200mi',
    match: 68,
    labels: [],
  },
  {
    id: 31,
    title: '2022 Toyota Camry Hybrid LE',
    price: 25_900,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '42,100mi',
    match: 61,
    labels: ['Low Price'],
  },
  {
    id: 32,
    title: '2023 Toyota Corolla Hatchback XSE',
    price: 26_500,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '16,300mi',
    match: 77,
    labels: ['Good Price'],
  },
  {
    id: 33,
    title: '2024 Toyota Venza Nightshade',
    price: 38_200,
    oldPrice: 40_900,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '7,500mi',
    match: 83,
    labels: ['Price Drop'],
  },
  {
    id: 34,
    title: '2021 Toyota RAV4 Prime SE',
    price: 37_500,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '29,800mi',
    match: 79,
    labels: [],
  },
  {
    id: 35,
    title: '2023 Toyota Highlander Bronze Edition',
    price: 44_200,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '13,400mi',
    match: 87,
    labels: ['Excellent Price'],
  },
  {
    id: 36,
    title: '2024 Toyota Tacoma Limited',
    price: 47_800,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '5,600mi',
    match: 90,
    labels: [],
  },
  {
    id: 37,
    title: '2022 Toyota Tundra SR5',
    price: 41_500,
    oldPrice: 44_200,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '33,700mi',
    match: 65,
    labels: ['Price Drop', 'Low Price'],
  },
  {
    id: 38,
    title: '2023 Toyota Prius XLE',
    price: 31_800,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '11,900mi',
    match: 81,
    labels: ['Good Price'],
  },
  {
    id: 39,
    title: '2024 Toyota 4Runner Limited',
    price: 51_200,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '3,800mi',
    match: 93,
    labels: [],
  },
  {
    id: 40,
    title: '2021 Toyota Sienna XLE',
    price: 36_900,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '38,500mi',
    match: 59,
    labels: ['Low Price'],
  },
  {
    id: 41,
    title: '2023 Toyota Crown Limited',
    price: 47_500,
    oldPrice: 50_800,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '10,200mi',
    match: 85,
    labels: ['Price Drop'],
  },
  {
    id: 42,
    title: '2024 Toyota GR86 Track',
    price: 33_900,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '2,400mi',
    match: 88,
    labels: ['Excellent Price'],
  },
  {
    id: 43,
    title: '2022 Toyota Supra 2.0',
    price: 44_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '19,600mi',
    match: 73,
    labels: [],
  },
  {
    id: 44,
    title: '2023 Toyota bZ4X XLE',
    price: 39_800,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '8,700mi',
    match: 80,
    labels: ['Good Price'],
  },
  {
    id: 45,
    title: '2024 Toyota Avalon Limited',
    price: 38_500,
    oldPrice: 41_200,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '4,100mi',
    match: 91,
    labels: ['Price Drop'],
  },
  {
    id: 46,
    title: '2021 Toyota C-HR Limited',
    price: 24_800,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '36,200mi',
    match: 56,
    labels: ['Low Price'],
  },
  {
    id: 47,
    title: '2023 Toyota Sequoia TRD Pro',
    price: 72_500,
    image: '/images/vehicles/rav4-white.png',
    miles: 'Park Place Toyota - 8.5mi',
    odometer: '12,800mi',
    match: 94,
    labels: ['Excellent Price'],
  },
  {
    id: 48,
    title: '2024 Toyota GR Corolla Circuit',
    price: 44_900,
    image: '/images/vehicles/corolla-cross.png',
    miles: 'Toyota of Irving - 5.7mi',
    odometer: '1,500mi',
    match: 97,
    labels: [],
  },
  {
    id: 49,
    title: '2022 Toyota Land Cruiser Heritage',
    price: 79_900,
    oldPrice: 85_500,
    image: '/images/vehicles/rav4-blue.png',
    miles: 'Toyota of Fort Worth - 6.1mi',
    odometer: '24,300mi',
    match: 89,
    labels: ['Price Drop'],
  },
  {
    id: 50,
    title: '2023 Toyota Mirai XLE',
    price: 48_200,
    image: '/images/vehicles/yaris-cross.png',
    miles: 'AutoNation Toyota - 3.2mi',
    odometer: '6,800mi',
    match: 70,
    labels: ['Good Price'],
  },
]
